/* Standalone test for audio_wav.c's real WAV decode + resample logic --
 * no GL, no ALSA, no MicroPython, same "prove the subsystem works in
 * isolation" precedent every other client test-main file in this
 * codebase already follows. Writes real, hand-constructed WAV files to disk (no
 * external tool/library involved -- genuine RIFF/WAVE bytes assembled by
 * hand) and reads them back through the real decoder, rather than
 * asserting against a canned/mocked byte buffer. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>
#include "audio_wav.h"

static int g_fail = 0;
static void check(int cond, const char *msg) {
    printf("  %s: %s\n", cond ? "PASS" : "FAIL", msg);
    if (!cond) g_fail = 1;
}

static void wr_u32le(FILE *f, uint32_t v) { unsigned char b[4] = {v&0xFF,(v>>8)&0xFF,(v>>16)&0xFF,(v>>24)&0xFF}; fwrite(b,1,4,f); }
static void wr_u16le(FILE *f, uint16_t v) { unsigned char b[2] = {v&0xFF,(v>>8)&0xFF}; fwrite(b,1,2,f); }

/* Writes a real, minimal, valid 16-bit PCM WAV file -- `channels` of
 * `frame_count` frames, each channel's samples generated by `gen` (so
 * the two test files below can each encode a distinguishable, checkable
 * signal per channel). */
static void write_wav(const char *path, int sample_rate, int channels, int frame_count,
                       int16_t (*gen)(int channel, int frame)) {
    FILE *f = fopen(path, "wb");
    int bytes_per_sample = 2;
    uint32_t data_bytes = (uint32_t)(frame_count * channels * bytes_per_sample);
    uint32_t riff_size = 4 + (8 + 16) + (8 + data_bytes);

    fwrite("RIFF", 1, 4, f); wr_u32le(f, riff_size); fwrite("WAVE", 1, 4, f);
    fwrite("fmt ", 1, 4, f); wr_u32le(f, 16);
    wr_u16le(f, 1);                                   /* PCM */
    wr_u16le(f, (uint16_t)channels);
    wr_u32le(f, (uint32_t)sample_rate);
    wr_u32le(f, (uint32_t)(sample_rate * channels * bytes_per_sample));  /* byte rate */
    wr_u16le(f, (uint16_t)(channels * bytes_per_sample));                /* block align */
    wr_u16le(f, 16);                                  /* bits per sample */
    fwrite("data", 1, 4, f); wr_u32le(f, data_bytes);
    for (int i = 0; i < frame_count; i++)
        for (int c = 0; c < channels; c++)
            wr_u16le(f, (uint16_t)gen(c, i));
    fclose(f);
}

static int16_t gen_mono_ramp(int channel, int frame) {
    (void)channel;
    return (int16_t)(frame * 330);   /* a simple, checkable increasing ramp, 0 -> ~32670 over 100 frames */
}

static int16_t gen_stereo_distinct(int channel, int frame) {
    (void)frame;
    return channel == 0 ? (int16_t)10000 : (int16_t)-10000;   /* left/right unmistakably different */
}

int main(void) {
    printf("[audio_wav_test] === 1: mono WAV, upmixed to stereo, resampled ===\n");
    write_wav("build/test_mono.wav", 8000, 1, 100, gen_mono_ramp);
    float *samples; int frames;
    int ok = phi_wav_load_resampled("build/test_mono.wav", 44100, &samples, &frames);
    check(ok, "loaded a real, valid mono 16-bit PCM WAV file");
    int expected_frames = (int)(100.0 * 44100.0 / 8000.0 + 0.5);
    check(frames > expected_frames - 3 && frames < expected_frames + 3,
          "resampled frame count matches the real 8000->44100 ratio (within rounding)");
    int mono_upmixed_ok = 1;
    for (int i = 0; i < frames; i++) if (samples[i*2+0] != samples[i*2+1]) { mono_upmixed_ok = 0; break; }
    check(mono_upmixed_ok, "a mono source's left/right output channels are real, identical duplicates (upmix), not garbage");
    check(samples[0] > -0.01f && samples[0] < 0.01f, "first sample is real, near-silent (ramp starts at 0)");
    check(samples[(frames-1)*2] > 0.5f, "last sample is real, near-full-scale (ramp ends near +32767/32768)");
    free(samples);

    printf("[audio_wav_test] === 2: stereo WAV, left/right genuinely distinct after resampling ===\n");
    write_wav("build/test_stereo.wav", 44100, 2, 50, gen_stereo_distinct);
    ok = phi_wav_load_resampled("build/test_stereo.wav", 44100, &samples, &frames);
    check(ok, "loaded a real, valid stereo 16-bit PCM WAV file");
    check(frames == 50, "same-rate resample (44100->44100) preserves the real frame count exactly");
    int distinct_ok = 1;
    for (int i = 0; i < frames; i++) {
        if (!(samples[i*2+0] > 0.29f && samples[i*2+0] < 0.31f)) distinct_ok = 0;
        if (!(samples[i*2+1] < -0.29f && samples[i*2+1] > -0.31f)) distinct_ok = 0;
    }
    check(distinct_ok, "real, distinct left (~+10000/32768) vs right (~-10000/32768) channel data survives the decode, not swapped or averaged");
    free(samples);

    printf("[audio_wav_test] === 3: real, honest failures -- missing file, malformed/unsupported format ===\n");
    ok = phi_wav_load_resampled("build/does_not_exist.wav", 44100, &samples, &frames);
    check(!ok && samples == NULL, "a missing file returns a real 0/NULL, not a crash");

    FILE *bad = fopen("build/test_not_wav.wav", "wb");
    fwrite("this is not a wav file at all, just text bytes", 1, 48, bad);
    fclose(bad);
    ok = phi_wav_load_resampled("build/test_not_wav.wav", 44100, &samples, &frames);
    check(!ok, "a non-WAV file (bad RIFF/WAVE magic) is rejected, not misread as garbage audio");

    /* A real WAV header claiming IEEE-float format (3), not PCM (1) --
     * this codebase's own stated scope only supports 16-bit PCM (see
     * audio_wav.h), so this must be a real, honest refusal. */
    FILE *f = fopen("build/test_badformat.wav", "wb");
    fwrite("RIFF", 1, 4, f); wr_u32le(f, 36); fwrite("WAVE", 1, 4, f);
    fwrite("fmt ", 1, 4, f); wr_u32le(f, 16);
    wr_u16le(f, 3); wr_u16le(f, 1); wr_u32le(f, 44100); wr_u32le(f, 44100*4); wr_u16le(f, 4); wr_u16le(f, 32);
    fwrite("data", 1, 4, f); wr_u32le(f, 0);
    fclose(f);
    ok = phi_wav_load_resampled("build/test_badformat.wav", 44100, &samples, &frames);
    check(!ok, "an IEEE-float-format WAV (unsupported per this codebase's real, stated scope) is rejected rather than misdecoded");

    if (g_fail) printf("\n[audio_wav_test] RESULT: FAIL\n");
    else printf("\n[audio_wav_test] RESULT: PASS (all checks passed)\n");
    return g_fail;
}
