#!/usr/bin/env python3
"""
Generates three hand-built test meshes for the Asset Browser / CRUD wire
protocol test pass (see phi.md's "Asset tracking and the Asset Browser
panel"): a pyramid, an (oblate) spheroid, and a cuboid. Follows the same
"hand-authored via a one-off script, POSITION+indices only, no external
tooling" precedent assets/cube.gltf itself was generated by.

Deliberately exercises BOTH glTF forms the CRUD protocol design commits
to supporting:
  - pyramid, spheroid -> loose .gltf + sibling .bin (like the existing
    hand-authored assets/cube.gltf)
  - cuboid            -> a single self-contained .glb (hand-rolled binary
    container -- the format the CRUD upload endpoint actually requires,
    see phi.md's "CRUD operates on .glb blobs only")

Every shape's winding is corrected programmatically (make_outward, below)
rather than hand-derived per face -- each face's normal is checked to
point away from the shape's centroid, matching the same "verify, don't
assume" discipline mesh_edit_test.c/fracture_test.c already established
for this codebase's other generated/mutated geometry (there: watertight-
ness + divergence-theorem volume checks; here: per-face outward-normal
+ a volume sanity check using the identical divergence-theorem formula
fracture_test.c's own volume() helper uses).

Usage: python3 tools/gen_test_assets.py
"""
import math
import struct
import os

OUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'assets', 'test')


# ---------------------------------------------------------------------------
# Small vector helpers (no numpy -- matches this project's "stdlib only"
# ethos on the Python side, same as server.py/assets_db.py)
# ---------------------------------------------------------------------------
def sub(a, b): return (a[0]-b[0], a[1]-b[1], a[2]-b[2])
def cross(a, b): return (a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0])
def dot(a, b): return a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
def avg3(a, b, c): return ((a[0]+b[0]+c[0])/3, (a[1]+b[1]+c[1])/3, (a[2]+b[2]+c[2])/3)


def make_outward(verts, tris, centroid):
    """For each (i0,i1,i2) triangle, flips to (i0,i2,i1) if that would make
    the face normal (same (b-a)x(c-a) formula meshobject.c's face_normal
    uses) point away from `centroid` more than the original order does --
    i.e. picks the winding that's actually outward-facing, rather than
    requiring it be hand-derived correctly for every face up front."""
    out = []
    for (i0, i1, i2) in tris:
        a, b, c = verts[i0], verts[i1], verts[i2]
        n = cross(sub(b, a), sub(c, a))
        face_c = avg3(a, b, c)
        d = dot(sub(face_c, centroid), n)
        out.append((i0, i1, i2) if d >= 0 else (i0, i2, i1))
    return out


def mesh_volume(verts, tris):
    """Divergence theorem, signed volume of a closed triangle mesh --
    identical formula to client/fracture_test_main.c's own volume() check.
    Positive iff winding is consistently outward."""
    v = 0.0
    for (i0, i1, i2) in tris:
        a, b, c = verts[i0], verts[i1], verts[i2]
        v += dot(a, cross(b, c))
    return v / 6.0


def check_all_outward(verts, tris, centroid, label):
    bad = 0
    for (i0, i1, i2) in tris:
        a, b, c = verts[i0], verts[i1], verts[i2]
        n = cross(sub(b, a), sub(c, a))
        face_c = avg3(a, b, c)
        if dot(sub(face_c, centroid), n) < -1e-6:
            bad += 1
    vol = mesh_volume(verts, tris)
    status = "PASS" if bad == 0 and vol > 0 else "FAIL"
    print(f"  {status}: {label}: {len(verts)} verts, {len(tris)} tris, "
          f"volume={vol:.2f}, {bad} inward-facing face(s)")
    return bad == 0 and vol > 0


# ---------------------------------------------------------------------------
# Shape builders -- each returns (verts: list[(x,y,z)], tris: list[(i0,i1,i2)])
# ---------------------------------------------------------------------------
def build_pyramid():
    hw, half_h = 8.0, 8.0   # 16x16 base, 16 tall -- centered on local origin
    verts = [
        (0.0, half_h, 0.0),                  # 0: apex
        (-hw, -half_h, -hw),                 # 1
        (hw, -half_h, -hw),                  # 2
        (hw, -half_h, hw),                   # 3
        (-hw, -half_h, hw),                  # 4
    ]
    tris = [
        (0, 1, 2), (0, 2, 3), (0, 3, 4), (0, 4, 1),   # 4 side faces
        (1, 2, 3), (1, 3, 4),                          # base (quad -> 2 tris)
    ]
    centroid = (0.0, 0.0, 0.0)   # approximate centroid of a square pyramid is fine for a winding check
    tris = make_outward(verts, tris, centroid)
    return verts, tris


def build_spheroid(rx=10.0, ry=6.0, rz=10.0, lon_segs=12, lat_segs=8):
    verts = [(0.0, ry, 0.0)]                       # 0: top pole
    ring_start = []
    for lat in range(1, lat_segs):
        theta = math.pi * lat / lat_segs
        ring_start.append(len(verts))
        for lon in range(lon_segs):
            phi = 2.0 * math.pi * lon / lon_segs
            x = rx * math.sin(theta) * math.cos(phi)
            y = ry * math.cos(theta)
            z = rz * math.sin(theta) * math.sin(phi)
            verts.append((x, y, z))
    bottom_pole = len(verts)
    verts.append((0.0, -ry, 0.0))

    tris = []
    top_ring = ring_start[0]
    for lon in range(lon_segs):
        a = top_ring + lon
        b = top_ring + (lon + 1) % lon_segs
        tris.append((0, a, b))
    for r in range(len(ring_start) - 1):
        r0, r1 = ring_start[r], ring_start[r+1]
        for lon in range(lon_segs):
            a0 = r0 + lon; a1 = r0 + (lon + 1) % lon_segs
            b0 = r1 + lon; b1 = r1 + (lon + 1) % lon_segs
            tris.append((a0, a1, b0))
            tris.append((a1, b1, b0))
    bottom_ring = ring_start[-1]
    for lon in range(lon_segs):
        a = bottom_ring + lon
        b = bottom_ring + (lon + 1) % lon_segs
        tris.append((bottom_pole, b, a))

    centroid = (0.0, 0.0, 0.0)   # exact, by symmetry
    tris = make_outward(verts, tris, centroid)
    return verts, tris


def build_cuboid():
    hx, hy, hz = 10.0, 3.0, 6.0   # 20 x 6 x 12 -- deliberately non-cube proportions
    verts = [
        (-hx, -hy, -hz), (hx, -hy, -hz), (hx, hy, -hz), (-hx, hy, -hz),  # back face  0-3
        (-hx, -hy,  hz), (hx, -hy,  hz), (hx, hy,  hz), (-hx, hy,  hz),  # front face 4-7
    ]
    tris = [
        (0, 1, 2), (0, 2, 3),   # back  (-z)
        (5, 4, 7), (5, 7, 6),   # front (+z)
        (4, 0, 3), (4, 3, 7),   # left  (-x)
        (1, 5, 6), (1, 6, 2),   # right (+x)
        (3, 2, 6), (3, 6, 7),   # top   (+y)
        (4, 5, 1), (4, 1, 0),   # bottom(-y)
    ]
    centroid = (0.0, 0.0, 0.0)
    tris = make_outward(verts, tris, centroid)
    return verts, tris


# ---------------------------------------------------------------------------
# glTF (loose JSON + .bin) writer -- mirrors client/halfedge_gltf.c's
# halfedge_save_gltf so the two hand-rolled JSON emitters describe the
# exact same shape of file.
# ---------------------------------------------------------------------------
def write_gltf_pair(name: str, verts, tris):
    pos_bytes = b''.join(struct.pack('<fff', *v) for v in verts)
    idx_bytes = b''.join(struct.pack('<HHH', *t) for t in tris)
    bin_bytes = pos_bytes + idx_bytes

    bin_name = f'{name}.bin'
    with open(os.path.join(OUT_DIR, bin_name), 'wb') as f:
        f.write(bin_bytes)

    xs = [v[0] for v in verts]; ys = [v[1] for v in verts]; zs = [v[2] for v in verts]
    gltf = f'''{{
  "asset": {{ "version": "2.0", "generator": "phi tools/gen_test_assets.py" }},
  "buffers": [ {{ "uri": "{bin_name}", "byteLength": {len(bin_bytes)} }} ],
  "bufferViews": [
    {{ "buffer": 0, "byteOffset": 0, "byteLength": {len(pos_bytes)}, "target": 34962 }},
    {{ "buffer": 0, "byteOffset": {len(pos_bytes)}, "byteLength": {len(idx_bytes)}, "target": 34963 }}
  ],
  "accessors": [
    {{ "bufferView": 0, "byteOffset": 0, "componentType": 5126, "count": {len(verts)}, "type": "VEC3",
       "min": [{min(xs)},{min(ys)},{min(zs)}], "max": [{max(xs)},{max(ys)},{max(zs)}] }},
    {{ "bufferView": 1, "byteOffset": 0, "componentType": 5123, "count": {len(tris)*3}, "type": "SCALAR" }}
  ],
  "meshes": [ {{ "primitives": [ {{ "attributes": {{ "POSITION": 0 }}, "indices": 1, "mode": 4 }} ] }} ],
  "nodes": [ {{ "mesh": 0 }} ],
  "scenes": [ {{ "nodes": [0] }} ],
  "scene": 0
}}
'''
    gltf_path = os.path.join(OUT_DIR, f'{name}.gltf')
    with open(gltf_path, 'w') as f:
        f.write(gltf)
    print(f"  wrote {gltf_path} + {bin_name} ({len(bin_bytes)} bytes)")


# ---------------------------------------------------------------------------
# GLB (single-file binary) writer -- hand-rolled per the Khronos glTF 2.0
# binary container spec (12-byte header + JSON chunk + BIN chunk, each
# chunk padded to a 4-byte boundary). No sibling .bin: buffer 0 has no
# "uri", its bytes are chunk 1 implicitly. cgltf.h (cgltf_file_type_glb)
# parses this transparently -- see phi.md's protocol design note.
# ---------------------------------------------------------------------------
def write_glb(name: str, verts, tris):
    pos_bytes = b''.join(struct.pack('<fff', *v) for v in verts)
    idx_bytes = b''.join(struct.pack('<HHH', *t) for t in tris)
    bin_data = pos_bytes + idx_bytes
    bin_pad = (4 - len(bin_data) % 4) % 4
    bin_chunk_data = bin_data + b'\x00' * bin_pad

    xs = [v[0] for v in verts]; ys = [v[1] for v in verts]; zs = [v[2] for v in verts]
    json_txt = (
        '{'
        '"asset":{"version":"2.0","generator":"phi tools/gen_test_assets.py"},'
        f'"buffers":[{{"byteLength":{len(bin_data)}}}],'
        f'"bufferViews":['
        f'{{"buffer":0,"byteOffset":0,"byteLength":{len(pos_bytes)},"target":34962}},'
        f'{{"buffer":0,"byteOffset":{len(pos_bytes)},"byteLength":{len(idx_bytes)},"target":34963}}'
        '],'
        f'"accessors":['
        f'{{"bufferView":0,"byteOffset":0,"componentType":5126,"count":{len(verts)},"type":"VEC3",'
        f'"min":[{min(xs)},{min(ys)},{min(zs)}],"max":[{max(xs)},{max(ys)},{max(zs)}]}},'
        f'{{"bufferView":1,"byteOffset":0,"componentType":5123,"count":{len(tris)*3},"type":"SCALAR"}}'
        '],'
        '"meshes":[{"primitives":[{"attributes":{"POSITION":0},"indices":1,"mode":4}]}],'
        '"nodes":[{"mesh":0}],'
        '"scenes":[{"nodes":[0]}],'
        '"scene":0'
        '}'
    ).encode('utf-8')
    json_pad = (4 - len(json_txt) % 4) % 4
    json_chunk_data = json_txt + b' ' * json_pad   # glTF spec: pad JSON chunk with spaces

    json_chunk = struct.pack('<II', len(json_chunk_data), 0x4E4F534A) + json_chunk_data   # 'JSON'
    bin_chunk  = struct.pack('<II', len(bin_chunk_data), 0x004E4942) + bin_chunk_data      # 'BIN\0'
    total_len = 12 + len(json_chunk) + len(bin_chunk)
    header = struct.pack('<4sII', b'glTF', 2, total_len)
    glb = header + json_chunk + bin_chunk

    glb_path = os.path.join(OUT_DIR, f'{name}.glb')
    with open(glb_path, 'wb') as f:
        f.write(glb)
    print(f"  wrote {glb_path} ({len(glb)} bytes)")


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    print("[gen_test_assets] verifying geometry (outward normals + positive volume)...")
    shapes = {
        'pyramid': build_pyramid(),
        'spheroid': build_spheroid(),
        'cuboid': build_cuboid(),
    }
    all_ok = True
    for name, (verts, tris) in shapes.items():
        all_ok &= check_all_outward(verts, tris, (0.0, 0.0, 0.0), name)
    if not all_ok:
        print("[gen_test_assets] RESULT: FAIL -- not writing files with bad geometry")
        return 1

    print("[gen_test_assets] writing files...")
    # pyramid/spheroid as loose .gltf+.bin (like the existing hand-authored
    # assets/cube.gltf) AND as .glb -- the CRUD upload endpoint only
    # accepts .glb (see phi.md's protocol design), so every shape needs a
    # .glb form to exercise the full create/list/load/update/delete cycle;
    # keeping the loose form too gives the loader test coverage across
    # both glTF forms, not just one.
    write_gltf_pair('pyramid', *shapes['pyramid'])
    write_glb('pyramid', *shapes['pyramid'])
    write_gltf_pair('spheroid', *shapes['spheroid'])
    write_glb('spheroid', *shapes['spheroid'])
    write_glb('cuboid', *shapes['cuboid'])
    print("[gen_test_assets] RESULT: PASS")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
